repos:
  - repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.6
        exclude: (^tests/|^.venv/|^venv/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-added-large-files
      - id: fix-encoding-pragma
      - id: flake8

